### ISSUE TITLE
sudo is invalid

### ISSUE THREAD

**Issue by forbiddennightmare** [po-devs/po-registry#3]

**Comment by SteveC688** [comment]
This bug report makes no sense. I'm also confused as to why you're attempting to build the registry as it is of no use to anyone except ourselves.

This version of the registry is depreciated anyway. Bug report closed.

**Comment by lamperi** [comment]
Isn't this more like future registry and not deprecated one ;)

**Comment by SteveC688** [comment]
Oh, I didn't notice coyotte uploaded the new code. My mistake!

Glad to see you're still alive Lamperi ;)

**Comment by coyotte508** [comment]
sudo is on linux. If you're on Windows you need to install nodejs, redis-server through chocolatey & all, and not use the sudo prefix.
